---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-watcher
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-watcher
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-watcher
subjects:
  - kind: ServiceAccount
    name: service-watcher
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forwussy-server
  namespace: default
  labels:
    app: forwussy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forwussy-server
  template:
    metadata:
      labels:
        app: forwussy-server
    spec:
      serviceAccountName: service-watcher
      containers:
        - name: forwussy-server
          image: evanjd711/forwussy:latest
          envFrom:
            - configMapRef:
                name: forwussy-cm
          imagePullPolicy: Always
          ports:
            - containerPort: 443
            - name: forwussy-certs

---
apiVersion: v1
kind: Service
metadata:
  name: forwussy-service
  namespace: default
  labels:
    app: forwussy-server
spec:
  selector:
    app: forwussy-server
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forwussy-cm
  namespace: default
data:
  ROUTER_IP: 10.0.0.1
  API_ENDPOINT: "/proxy/network/api/s/default/rest/portforward"
  API_KEY: <API_KEY>
